---
- name: Check Availability of Website
  hosts: all
  sources:
    - name: URL Checking
      ansible.eda.url_check:
        urls:
          - "{{ url }}"
        delay: "{{ delay_seconds }}"
  rules:
    - name: Say the site is up
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: "The site is up"
    - name: Say the site is down # Enable action later to run a job template
      condition: event.url_check.status == "down"
      action:
        debug:
          msg: "The site is down"
#         run_job_template:
#           name: "{{ jobTemplate }}"
#           organization: "{{ org }}"
