---
- name: Dump EDA Webhook Contents
  hosts: all
  gather_facts: false
  tasks:

    - name: Output received payload
      ansible.builtin.debug:
        var: ansible_eda.event.payload
      delegate_to: localhost
      run_once: true
